## Question 1

In [20]:
# Python program to implement Runge Kutta method
# A sample differential equation "dy / dt = (-2yt)"
def dydt(y, t):
    return ((-2*y*t))

# Finds value of y for a given t using step size h
# and initial value y0 at t0.
def rungeKutta(t0, y0, t, h):
    # Count number of iterations using step size or
    # step height
    n = int((t - t0)/h)
    # Iterate for number of iterations
    y = y0
    for i in range(1, n + 1):
        # Apply Runge Kutta Formulas to find next value of y
        k1 = h * dydt(t0, y)
        k2 = h * dydt(t0 + 0.5 * h, y + 0.5 * k1)
        k3 = h * dydt(t0 + 0.5 * h, y + 0.5 * k2)
        k4 = h * dydt(t0 + h, y + k3)
        
        # Update next value of y
        y = y + (1.0 / 6.0)*(k1 + 2 * k2 + 2 * k3 + k4)
        
        # Update next value of t
        t0 = t0 + h
    return y

# Driver method
t0 = 0
y = 1
t = 2
h = 0.2
print('The value of y at t is:', rungeKutta(t0, y, t, h))

import math #import the entire library
from matplotlib import pyplot as plt #import only certain part of the library
t = list(range(0,2)) #output will be 0 to 2
y= rungeKutta(t0, y, t, h)
for num in t:

 plt.plot(x,y, color='pink')
plt.title('Solving ODE')
plt.xlabel("t values from 0 to 2")
plt.ylabel("y(t)")
plt.show()


The value of y at t is: 0.01845769414541351


TypeError: unsupported operand type(s) for -: 'list' and 'int'

## Question 2

In [1]:
# Import necessary libraries
import numpy as np
import scipy as sc
# Define the coefficient matrix A
A = np.array([[2, 4, 6], [5, 3, 2], [7, 8, 9]])
print(A)
# Define the right-hand side vector b
b = np.array([[18], [13], [30]])
print(b)
# Calculate the inverse of A and multiply by b to find the solution vector
C = sc.linalg.inv(A).dot(b)
print(C)
# Alternatively, use the solve function to find the solution vector directly
D = sc.linalg.solve(A, b)
print(D)



[[2 4 6]
 [5 3 2]
 [7 8 9]]
[[18]
 [13]
 [30]]
[[ 4.5]
 [-7.5]
 [ 6.5]]
[[ 4.5]
 [-7.5]
 [ 6.5]]


## Question 3

In [15]:
import json
import requests

# Function to get the population of a state
def get_population(number_days, dataset):
    for days in dataset:
        if days['days'] == number_days:
            return state['temperature']
    return None

# Function to load the dataset from a JSON file or URL
def load_dataset(data_source):
    if data_source.startswith('http'):
        response = requests.get(data_source)
        dataset = response.json()
    else:
        with open(data_source, 'r') as file:
            dataset = json.load(file)
    return dataset

# Main function
def main():
    # Provide the path or URL to your dataset JSON file
    dataset_source1= "https://api.open-meteo.com/v1/forecast?.json"  # Replace with your actual file path or URL
    dataset_source2="latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1.json"



    # Load the dataset
    state_dataset = load_dataset(dataset_source)

    while True:
        # Get user input
        number_days = input("Enter the number of days(1 until 16 only) (type 'quit' to exit): ")

        # Check for exit condition
        if number_days.lower() > '16':
            print("Read the instruction and check your input")
            else
                 break

        # Get the temperature
        temperature = get_temperature(number_days, state_dataset)

        # Display the result
        if temperature is not None:
            print(f"Temperature of day {number_days}: {temperature}")
        else
            print(f"Day {number_days} is not found in the data.")

# Run the script
if __name__ == "__main__":
    main()
    
import math #import the entire library
from matplotlib import pyplot as plt #import only certain part of the library
x = list(range(1,16)) #output will be 0 to 16
y= temperature

plt.plot(x,y, color='pink')
plt.title('')
plt.xlabel("Numbers of forecast days")
plt.ylabel("Hourly temperature data")
plt.show()


SyntaxError: invalid syntax (2798358627.py, line 39)